AWSTemplateFormatVersion: "2010-09-09"
Description: 'My Private Subnet description'
Resources:
  privateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'ap-southeast-1a'
      CidrBlock: '172.31.48.0/20'
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: 'Name'
          Value: 'default-private-subnet1'
        - Key: 'Region'
          Value: 'Singapore'
        - Key: 'Environment'
          Value: 'Non Production'
      VpcId: 'vpc-067addfe7b15a5b0d'
  routeTableForPrivateSubnet1:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'Route Table For Private Subnet 1'
        - Key: 'Region'
          Value: 'Singapore'
        - Key: 'Environment'
          Value: 'Non Production'
      VpcId: 'vpc-067addfe7b15a5b0d'
  privateSubnet1RTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        !Ref privateSubnet1
      RouteTableId: 
        !Ref routeTableForPrivateSubnet1


  privateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'ap-southeast-1b'
      CidrBlock: '172.31.64.0/20'
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: 'Name'
          Value: 'default-private-subnet2'
        - Key: 'Region'
          Value: 'Singapore'
        - Key: 'Environment'
          Value: 'Non Production'
      VpcId: 'vpc-067addfe7b15a5b0d'
  routeTableForPrivateSubnet2:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'Route Table For Private Subnet 2'
        - Key: 'Region'
          Value: 'Singapore'
        - Key: 'Environment'
          Value: 'Non Production'
      VpcId: 'vpc-067addfe7b15a5b0d'
  privateSubnet2RTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        !Ref privateSubnet2
      RouteTableId: 
        !Ref routeTableForPrivateSubnet2

  privateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'ap-southeast-1c'
      CidrBlock: '172.31.80.0/20'
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: 'Name'
          Value: 'default-private-subnet3'
        - Key: 'Region'
          Value: 'Singapore'
        - Key: 'Environment'
          Value: 'Non Production'
      VpcId: 'vpc-067addfe7b15a5b0d'
  routeTableForPrivateSubnet3:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'Route Table For Private Subnet 3'
        - Key: 'Region'
          Value: 'Singapore'
        - Key: 'Environment'
          Value: 'Non Production'
      VpcId: 'vpc-067addfe7b15a5b0d'
  privateSubnet3RTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        !Ref privateSubnet3
      RouteTableId: 
        !Ref routeTableForPrivateSubnet3

  privateSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'ap-southeast-1a'
      CidrBlock: '172.31.96.0/20'
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: 'Name'
          Value: 'default-private-subnet4'
        - Key: 'Region'
          Value: 'Singapore'
        - Key: 'Environment'
          Value: 'Non Production'
      VpcId: 'vpc-067addfe7b15a5b0d'
  routeTableForPrivateSubnet4:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'Route Table For Private Subnet 4'
        - Key: 'Region'
          Value: 'Singapore'
        - Key: 'Environment'
          Value: 'Non Production'
      VpcId: 'vpc-067addfe7b15a5b0d'
  privateSubnet4RTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        !Ref privateSubnet4
      RouteTableId: 
        !Ref routeTableForPrivateSubnet4